/* Copyright 2017 David Li.

 * This file is part of BigRedRPG.

 * BigRedRPG is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.

 * BigRedRPG is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with BigRedRPG.  If not, see <http://www.gnu.org/licenses/>.
 */

import Student from "../student";
import * as random from "../random";

export const MAJOR_LIST = [
    "Africana Studies",
    "Agricultural Sciences",
    "American Studies",
    "Animal Science",
    "Anthropology",
    "Applied Economics and Management",
    "Archaeology",
    "Architecture",
    "Asian Studies",
    "Astronomy",
    "Atmospheric Science",
    "Biological Engineering",
    "Biological Sciences",
    "Biology and Society",
    "Biomedical Engineering",
    "Biometry and Statistics",
    "Chemical Engineering",
    "Chemistry and Chemical Biology",
    "China and Asia-Pacific Studies",
    "Civil Engineering",
    "Classics",
    "College Scholar Program",
    "Communication",
    "Comparative Literature",
    "Computer Science",
    "Design and Environmental Analysis",
    "Development Sociology",
    "Economics",
    "Electrical and Computer Engineering",
    "Engineering Physics",
    "English",
    "Entomology",
    "Environmental and Sustainability Sciences",
    "Environmental Engineering",
    "Feminist, Gender & Sexuality Studies",
    "Fiber Science and Apparel Design",
    "Fine Arts",
    "Food Science",
    "French",
    "German",
    "German Area Studies",
    "Global and Public Health Sciences",
    "Government",
    "History",
    "History of Art",
    "Hotel Administration",
    "Human Biology, Health and Society",
    "Human Development",
    "Independent Major",
    "Industrial and Labor Relations",
    "Information Science",
    "Interdisciplinary Studies",
    "International Agriculture and Rural Development",
    "Italian",
    "Landscape Architecture",
    "Linguistics",
    "Materials Science and Engineering",
    "Mathematics",
    "Mechanical Engineering",
    "Music",
    "Near Eastern Studies",
    "Nutritional Sciences",
    "Operations Research and Engineering",
    "Performing and Media Arts",
    "Philosophy",
    "Physics",
    "Plant Science",
    "Policy Analysis and Management",
    "Psychology",
    "Religious Studies",
    "Science and Technology Studies",
    "Science of Earth Systems",
    "Sociology",
    "Spanish",
    "Statistical Science",
    "Urban and Regional Studies",
    "Viticulture and Enology",
];

// TODO: names are not very diverse
export const FIRST_NAME_LIST = [
    "Adell",
    "Aja",
    "Alfonzo",
    "Alvera",
    "Assunta",
    "Britteny",
    "Carline",
    "Cliff",
    "Coletta",
    "Darcy",
    "Del",
    "Delisa",
    "Dennise",
    "Elida",
    "Elroy",
    "Evie",
    "Gerardo",
    "Glady",
    "Idell",
    "Jeff",
    "Jeniffer",
    "Jone",
    "Karin",
    "Kaylene",
    "Kimbra",
    "Lani",
    "Larae",
    "Lashanda",
    "Margorie",
    "Marybelle",
    "Marylou",
    "Milford",
    "Na",
    "Patrick",
    "Rico",
    "Rossana",
    "Seema",
    "Setsuko",
    "Sharika",
    "Sharyl",
    "Sheryl",
    "Sindy",
    "Susanna",
    "Tiffanie",
    "Vernon",
    "Vonnie",
    "Wendi",
    "Wilma",
    "Yahaira",
    "Yon",
];
export const LAST_NAME_LIST = [
    "Adams",
    "Allen",
    "Anderson",
    "Baker",
    "Bell",
    "Brown",
    "Campbell",
    "Clark",
    "Cook",
    "County",
    "Davis",
    "Edwards",
    "Evans",
    "Green",
    "Hall",
    "Harris",
    "Hill",
    "Jackson",
    "James",
    "John",
    "Johnson",
    "Jones",
    "King",
    "Lee",
    "Lewis",
    "Martin",
    "Mc",
    "Miller",
    "Mitchell",
    "Moore",
    "Morris",
    "Parker",
    "Roberts",
    "Robinson",
    "Scott",
    "Smith",
    "Stewart",
    "Taylor",
    "Thomas",
    "Thompson",
    "Tryniski",
    "Turner",
    "Walker",
    "Ward",
    "White",
    "Williams",
    "Wilson",
    "Wood",
    "Wright",
    "Young",
];

export function randomStudent(dorms: string[]): Student {
    let id = Student.newId();

    let dorm = random.choice(dorms);

    let firstname = random.choice(FIRST_NAME_LIST);
    let lastname = random.choice(LAST_NAME_LIST);

    let student = new Student(id, `${firstname} ${lastname}`, random.choice(MAJOR_LIST), dorm);

    return student;
}
